export default [
  {
    "_id": "Q101",
    "title": "React Introduction Quiz",
    "course": "RS101",
    "available": "2026-04-16",
    "due": "May 13 at 11:59 pm",
    "until": "May 13 at 11:59 pm",
    "points": 40,
    "questions": 5,
    "desc": "New Quiz Description",
    "published": false,
    "score": 0,
    "quizType": "Graded Quiz",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": false,
    "numberOfAttempts": 1,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfter": false
  },
  {
    "_id": "Q102",
    "title": "React Detailed Quiz",
    "course": "RS101",
    "available": "2026-04-13",
    "due": "2026-04-14",
    "until": "May 13 at 11:59 pm",
    "points": 60,
    "questions": 9,
    "desc": "New Quiz Description",
    "published": false,
    "score": 0,
    "quizType": "Graded Quiz",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": false,
    "numberOfAttempts": 1,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfter": false
  },
  {
    "_id": "Q103",
    "title": "History of Matcha Quiz",
    "course": "MM101",
    "available": "2026-04-15",
    "due": "2026-04-18",
    "until": "",
    "points": 60,
    "questions": 9,
    "desc": "New Quiz Description",
    "published": true,
    "score": 0,
    "quizType": "Graded Quiz",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": false,
    "numberOfAttempts": 1,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfter": false
  }
];