export default [
    
        {
          "_id": "123",
          "username": "iron_man",
          "password": "stark123",
          "firstName": "Tony ",
          "lastName": "Stark",
          "email": "tony@stark.com",
          "dob": "1970-05-29T00:00:00.000Z",
          "role": "FACULTY",
          "loginId": "001234561S",
          "section": "S101",
          "lastActivity": "2020-10-01",
          "totalActivity": "10:21:32"
        },
        {
          "_id": "234",
          "username": "dark_knight",
          "password": "wayne123",
          "firstName": "Bruce ",
          "lastName": "Wayne",
          "email": "bruce@wayne.com",
          "dob": "1972-02-19",
          "role": "STUDENT",
          "loginId": "001234562S",
          "section": "S101",
          "lastActivity": "2020-11-02",
          "totalActivity": "15:32:43"
        },
        {
          "_id": "345",
          "username": "black_widow",
          "password": "romanoff123",
          "firstName": "Natasha ",
          "lastName": "Romanoff",
          "email": "natasha@avengers.com",
          "dob": "1984-11-22",
          "role": "TA",
          "loginId": "001234564S",
          "section": "S101",
          "lastActivity": "2020-11-05",
          "totalActivity": "13:23:34"
        },
        {
          "_id": "456",
          "username": "thor_odinson",
          "password": "mjolnir123",
          "firstName": "Thor ",
          "lastName": "Odinson",
          "email": "thor@asgard.com",
          "dob": "982-05-25",
          "role": "STUDENT",
          "loginId": "001234565S",
          "section": "S101",
          "lastActivity": "2020-12-01",
          "totalActivity": "11:22:33"
        },
        {
          "_id": "567",
          "username": "hulk_smash",
          "password": "banner123",
          "firstName": "Bruce ",
          "lastName": "Banner",
          "email": "bruce@avengers.com",
          "dob": "1969-12-18",
          "role": "STUDENT",
          "loginId": "001234566S",
          "section": "S101",
          "lastActivity": "2020-12-01",
          "totalActivity": "22:33:44"
        },
        {
          "_id": "678",
          "username": "ring_bearer",
          "password": "shire123",
          "firstName": "Frodo ",
          "lastName": "Baggins",
          "email": "frodo@shire.com",
          "dob": "1368-09-22",
          "role": "FACULTY",
          "loginId": "001234567S",
          "section": "S101",
          "lastActivity": "2020-12-02",
          "totalActivity": "44:33:22"
        },
        {
          "_id": "789",
          "username": "strider",
          "password": "aragorn123",
          "firstName": "Aragorn ",
          "lastName": "Elessar",
          "email": "aragorn@gondor.com",
          "dob": "2931-03-01",
          "role": "TA",
          "loginId": "001234568S",
          "section": "S101",
          "lastActivity": "2020-12-04",
          "totalActivity": "12:23:34"
        },
        {
          "_id": "890",
          "username": "elf_archer",
          "password": "legolas123",
          "firstName": "Legolas ",
          "lastName": "Greenleaf",
          "email": "legolas@mirkwood.com",
          "dob": "2879-07-15",
          "role": "STUDENT",
          "loginId": "001234569S",
          "section": "S101",
          "lastActivity": "2020-11-11",
          "totalActivity": "21:32:43"
        },
    
        {
          "_id": "891",
          "username": "hello_there",
          "password": "legolas123",
          "firstName": "Melanie ",
          "lastName": "Hammond",
          "email": "mhammond@mirkwood.com",
          "dob": "2879-07-15",
          "role": "STUDENT",
          "loginId": "001234569S",
          "section": "S101",
          "lastActivity": "2020-11-11",
          "totalActivity": "21:32:43"
        },
        {
          "_id": "777",
          "username": "ada",
          "password": "123",
          "firstName": "Ada ",
          "lastName": "Lovelace",
          "email": "ada@lovelace.com",
          "dob": "1815-12-15",
          "role": "ADMIN",
          "loginId": "002143650S",
          "section": "S101",
          "lastActivity": "1852-11-27",
          "totalActivity": "21:32:43"
        },
    
        {
          "_id": "892",
          "username": "spider_peter",
          "password": "webswing",
          "firstName": "Peter ",
          "lastName": "Parker",
          "email": "peter@avengers.com",
          "dob": "2001-08-10",
          "role": "STUDENT",
          "loginId": "001234570S",
          "section": "S101",
          "lastActivity": "2024-10-01",
          "totalActivity": "19:12:45"
        },
        {
          "_id": "893",
          "username": "scarlet_wanda",
          "password": "chaosMagic7",
          "firstName": "Wanda ",
          "lastName": "Maximoff",
          "email": "wanda@maximoff.com",
          "dob": "1989-02-10",
          "role": "TA",
          "loginId": "001234571T",
          "section": "S101",
          "lastActivity": "2024-10-03",
          "totalActivity": "28:44:11"
        },
        {
          "_id": "894",
          "username": "falcon_sam",
          "password": "hellolalala",
          "firstName": "Sam ",
          "lastName": "Wilson",
          "email": "falcon@avengers.com",
          "dob": "1979-09-23",
          "role": "FACULTY",
          "loginId": "001234572F",
          "section": "S101",
          "lastActivity": "2024-10-08",
          "totalActivity": "51:03:22"
        },
        {
          "_id": "895",
          "username": "ant_scott",
          "password": "quantumJump5",
          "firstName": "Scott ",
          "lastName": "Lang",
          "email": "scott@lang.com",
          "dob": "1979-04-06",
          "role": "STUDENT",
          "loginId": "001234573S",
          "section": "S101",
          "lastActivity": "2024-09-29",
          "totalActivity": "13:55:09"
        },
        {
          "_id": "896",
          "username": "captain_marvel",
          "password": "photonBlast88",
          "firstName": "Carol ",
          "lastName": "Danvers",
          "email": "carol@avengers.com",
          "dob": "1985-07-17",
          "role": "FACULTY",
          "loginId": "001234574F",
          "section": "S101",
          "lastActivity": "2024-10-11",
          "totalActivity": "63:21:44"
        },
        {
          "_id": "897",
          "username": "winter_bucky",
          "password": "vibraniumArm",
          "firstName": "Bucky ",
          "lastName": "Barnes",
          "email": "bucky@barnes.com",
          "dob": "1917-03-10",
          "role": "TA",
          "loginId": "001234575T",
          "section": "S101",
          "lastActivity": "2024-10-05",
          "totalActivity": "34:19:28"
        },
        {
          "_id": "898",
          "username": "black_panther",
          "password": "wakandaForever",
          "firstName": "TChalla ",
          "lastName": "Udaku",
          "email": "tchalla@avengers.com",
          "dob": "1980-11-29",
          "role": "FACULTY",
          "loginId": "001234576F",
          "section": "S101",
          "lastActivity": "2024-10-07",
          "totalActivity": "70:45:12"
        },
        {
          "_id": "899",
          "username": "shuri_tech",
          "password": "vibraniumLab",
          "firstName": "Shuri ",
          "lastName": "Udaku",
          "email": "shuri@udaku.com",
          "dob": "2003-05-12",
          "role": "STUDENT",
          "loginId": "001234577S",
          "section": "S101",
          "lastActivity": "2024-10-02",
          "totalActivity": "22:31:18"
        },
        {
          "_id": "900",
          "username": "star_lord",
          "password": "awesomeMix1",
          "firstName": "Peter ",
          "lastName": "Quill",
          "email": "quill@avengers.com",
          "dob": "1980-02-04",
          "role": "STUDENT",
          "loginId": "001234578S",
          "section": "S101",
          "lastActivity": "2024-09-28",
          "totalActivity": "17:42:55"
        },
        {
          "_id": "901",
          "username": "mantis_empath",
          "password": "feelings888",
          "firstName": "Mantis ",
          "lastName": "Celestia",
          "email": "mantis@celestia.com",
          "dob": "1995-06-20",
          "role": "TA",
          "loginId": "001234579T",
          "section": "S101",
          "lastActivity": "2024-10-06",
          "totalActivity": "26:14:37"
        },
        {
          "_id": "902",
          "username": "rocket_raccoon",
          "password": "blasterTech9",
          "firstName": "Rocket ",
          "lastName": "Raccoon",
          "email": "rocket_raccoon@marvel.com",
          "dob": "1998-06-20",
          "role": "TA",
          "loginId": "00123479T",
          "section": "S101",
          "lastActivity": "2024-10-06",
          "totalActivity": "26:14:37"
        }
      
];